import openmc
from cells import cells, surfaces

###############################################################################
#                     Create a dictionary of all shared universes
###############################################################################

# Instantiate Universes
universes = {}

universes['SS Sheet Cross Core 11']      = openmc.Universe(name='SS Sheet Cross Core 11')
universes['SS Sheet Horiz Core 11']      = openmc.Universe(name='SS Sheet Horiz Core 11')
universes['SS Sheet Verti Core 11']      = openmc.Universe(name='SS Sheet Verti Core 11')
universes['SS Sheet Cross Core 12']      = openmc.Universe(name='SS Sheet Cross Core 12')
universes['SS Sheet Horiz Core 12']      = openmc.Universe(name='SS Sheet Horiz Core 12')
universes['SS Sheet Verti Core 12']      = openmc.Universe(name='SS Sheet Verti Core 12')
universes['BAl Sheet Cross Core 13']     = openmc.Universe(name='BAl Sheet Cross Core 13')
universes['BAl Sheet Horiz Core 13']     = openmc.Universe(name='BAl Sheet Horiz Core 13')
universes['BAl Sheet Verti Core 13']     = openmc.Universe(name='BAl Sheet Verti Core 13')
universes['BAl Sheet Cross Core 14']     = openmc.Universe(name='BAl Sheet Cross Core 14')
universes['BAl Sheet Horiz Core 14']     = openmc.Universe(name='BAl Sheet Horiz Core 14')
universes['BAl Sheet Verti Core 14']     = openmc.Universe(name='BAl Sheet Verti Core 14')
universes['BAl Sheet Cross Core 15']     = openmc.Universe(name='BAl Sheet Cross Core 15')
universes['BAl Sheet Horiz Core 15']     = openmc.Universe(name='BAl Sheet Horiz Core 15')
universes['BAl Sheet Verti Core 15']     = openmc.Universe(name='BAl Sheet Verti Core 15')
universes['BAl Sheet Cross Core 16']     = openmc.Universe(name='BAl Sheet Cross Core 16')
universes['BAl Sheet Horiz Core 16']     = openmc.Universe(name='BAl Sheet Horiz Core 16')
universes['BAl Sheet Verti Core 16']     = openmc.Universe(name='BAl Sheet Verti Core 16')
universes['BAl Sheet Cross Core 17']     = openmc.Universe(name='BAl Sheet Cross Core 17')
universes['BAl Sheet Horiz Core 17']     = openmc.Universe(name='BAl Sheet Horiz Core 17')
universes['BAl Sheet Verti Core 17']     = openmc.Universe(name='BAl Sheet Verti Core 17')
universes['BAl Sheet Cross Core 18']     = openmc.Universe(name='BAl Sheet Cross Core 18')
universes['BAl Sheet Horiz Core 18']     = openmc.Universe(name='BAl Sheet Horiz Core 18')
universes['BAl Sheet Verti Core 18']     = openmc.Universe(name='BAl Sheet Verti Core 18')
universes['BAl Sheet Cross Core 19']     = openmc.Universe(name='BAl Sheet Cross Core 19')
universes['BAl Sheet Horiz Core 19']     = openmc.Universe(name='BAl Sheet Horiz Core 19')
universes['BAl Sheet Verti Core 19']     = openmc.Universe(name='BAl Sheet Verti Core 19')
universes['BAl Sheet Cross Core 20']     = openmc.Universe(name='BAl Sheet Cross Core 20')
universes['BAl Sheet Horiz Core 20']     = openmc.Universe(name='BAl Sheet Horiz Core 20')
universes['BAl Sheet Verti Core 20']     = openmc.Universe(name='BAl Sheet Verti Core 20')
universes['BAl Sheet Cross Core 21']     = openmc.Universe(name='BAl Sheet Cross Core 21')
universes['BAl Sheet Horiz Core 21']     = openmc.Universe(name='BAl Sheet Horiz Core 21')
universes['BAl Sheet Verti Core 21']     = openmc.Universe(name='BAl Sheet Verti Core 21')

universes['Fuel Rod Core 1']             = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 2']             = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 3']             = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 4']             = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 5']             = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 6']             = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 7']             = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 8']             = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 9']             = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 10']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 11']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 12']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 13']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 14']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 15']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 16']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 17']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 18']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 19']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 20']            = openmc.Universe(name='Fuel Rod')
universes['Fuel Rod Core 21']            = openmc.Universe(name='Fuel Rod')


universes['Al Rod Core 1']               = openmc.Universe(name='Al Rod')
universes['Al Rod Core 2']               = openmc.Universe(name='Al Rod')
universes['Al Rod Core 3']               = openmc.Universe(name='Al Rod')
universes['Al Rod Core 4']               = openmc.Universe(name='Al Rod')
universes['Al Rod Core 5']               = openmc.Universe(name='Al Rod')
universes['Al Rod Core 6']               = openmc.Universe(name='Al Rod')
universes['Al Rod Core 7']               = openmc.Universe(name='Al Rod')
universes['Al Rod Core 8']               = openmc.Universe(name='Al Rod')
universes['Al Rod Core 9']               = openmc.Universe(name='Al Rod')
universes['Al Rod Core 10']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 11']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 12']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 13']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 14']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 15']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 16']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 17']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 18']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 19']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 20']              = openmc.Universe(name='Al Rod')
universes['Al Rod Core 21']              = openmc.Universe(name='Al Rod')

universes['B4C Rod Core 1']              = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 2']              = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 3']              = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 4']              = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 5']              = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 6']              = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 7']              = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 8']              = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 9']              = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 10']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 11']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 12']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 13']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 14']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 15']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 16']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 17']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 18']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 19']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 20']             = openmc.Universe(name='B4C Rod')
universes['B4C Rod Core 21']             = openmc.Universe(name='B4C Rod')

universes['Reflector Core 1']            = openmc.Universe(name='Reflector Core 1')
universes['Reflector Core 2']            = openmc.Universe(name='Reflector Core 2')
universes['Reflector Core 3']            = openmc.Universe(name='Reflector Core 3')
universes['Reflector Core 4']            = openmc.Universe(name='Reflector Core 4')
universes['Reflector Core 5']            = openmc.Universe(name='Reflector Core 5')
universes['Reflector Core 6']            = openmc.Universe(name='Reflector Core 6')
universes['Reflector Core 7']            = openmc.Universe(name='Reflector Core 7')
universes['Reflector Core 8']            = openmc.Universe(name='Reflector Core 8')
universes['Reflector Core 9']            = openmc.Universe(name='Reflector Core 9')
universes['Reflector Core 10']           = openmc.Universe(name='Reflector Core 10')
universes['Reflector Core 11']           = openmc.Universe(name='Reflector Core 11')
universes['Reflector Core 12']           = openmc.Universe(name='Reflector Core 12')
universes['Reflector Core 13']           = openmc.Universe(name='Reflector Core 13')
universes['Reflector Core 14']           = openmc.Universe(name='Reflector Core 14')
universes['Reflector Core 15']           = openmc.Universe(name='Reflector Core 15')
universes['Reflector Core 16']           = openmc.Universe(name='Reflector Core 16')
universes['Reflector Core 17']           = openmc.Universe(name='Reflector Core 17')
universes['Reflector Core 18']           = openmc.Universe(name='Reflector Core 18')
universes['Reflector Core 19']           = openmc.Universe(name='Reflector Core 19')
universes['Reflector Core 20']           = openmc.Universe(name='Reflector Core 20')
universes['Reflector Core 21']           = openmc.Universe(name='Reflector Core 21')

universes['Root Core 1']                 = openmc.Universe(universe_id=0,  name='Root Core 1')
universes['Root Core 2']                 = openmc.Universe(universe_id=0,  name='Root Core 2')
universes['Root Core 3']                 = openmc.Universe(universe_id=0,  name='Root Core 3')
universes['Root Core 4']                 = openmc.Universe(universe_id=0,  name='Root Core 4')
universes['Root Core 5']                 = openmc.Universe(universe_id=0,  name='Root Core 5')
universes['Root Core 6']                 = openmc.Universe(universe_id=0,  name='Root Core 6')
universes['Root Core 7']                 = openmc.Universe(universe_id=0,  name='Root Core 7')
universes['Root Core 8']                 = openmc.Universe(universe_id=0,  name='Root Core 8')
universes['Root Core 9']                 = openmc.Universe(universe_id=0,  name='Root Core 9')
universes['Root Core 10']                = openmc.Universe(universe_id=0,  name='Root Core 10')
universes['Root Core 11']                = openmc.Universe(universe_id=0,  name='Root Core 11')
universes['Root Core 12']                = openmc.Universe(universe_id=0,  name='Root Core 12')
universes['Root Core 13']                = openmc.Universe(universe_id=0,  name='Root Core 13')
universes['Root Core 14']                = openmc.Universe(universe_id=0,  name='Root Core 14')
universes['Root Core 15']                = openmc.Universe(universe_id=0,  name='Root Core 15')
universes['Root Core 16']                = openmc.Universe(universe_id=0,  name='Root Core 16')
universes['Root Core 17']                = openmc.Universe(universe_id=0,  name='Root Core 17')
universes['Root Core 18']                = openmc.Universe(universe_id=0,  name='Root Core 18')
universes['Root Core 19']                = openmc.Universe(universe_id=0,  name='Root Core 19')
universes['Root Core 20']                = openmc.Universe(universe_id=0,  name='Root Core 20')
universes['Root Core 21']                = openmc.Universe(universe_id=0,  name='Root Core 21')

# Register Cells with Universes
universes['Root Core 1']      .add_cell(cells['Core 1'])
universes['Root Core 2']      .add_cell(cells['Core 2'])
universes['Root Core 3']      .add_cell(cells['Core 3'])
universes['Root Core 4']      .add_cell(cells['Core 4'])
universes['Root Core 5']      .add_cell(cells['Core 5'])
universes['Root Core 6']      .add_cell(cells['Core 6'])
universes['Root Core 7']      .add_cell(cells['Core 7'])
universes['Root Core 8']      .add_cell(cells['Core 8'])
universes['Root Core 9']      .add_cell(cells['Core 9'])
universes['Root Core 10']     .add_cell(cells['Core 10'])
universes['Root Core 11']     .add_cell(cells['Core 11'])
universes['Root Core 12']     .add_cell(cells['Core 12'])
universes['Root Core 13']     .add_cell(cells['Core 13'])
universes['Root Core 14']     .add_cell(cells['Core 14'])
universes['Root Core 15']     .add_cell(cells['Core 15'])
universes['Root Core 16']     .add_cell(cells['Core 16'])
universes['Root Core 17']     .add_cell(cells['Core 17'])
universes['Root Core 18']     .add_cell(cells['Core 18'])
universes['Root Core 19']     .add_cell(cells['Core 19'])
universes['Root Core 20']     .add_cell(cells['Core 20'])
universes['Root Core 21']     .add_cell(cells['Core 21'])


universes['Fuel Rod Core 1']  .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 1']])
universes['Fuel Rod Core 2']  .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 2']])
universes['Fuel Rod Core 3']  .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 3']])
universes['Fuel Rod Core 4']  .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 4']])
universes['Fuel Rod Core 5']  .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 5']])
universes['Fuel Rod Core 6']  .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 6']])
universes['Fuel Rod Core 7']  .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 7']])
universes['Fuel Rod Core 8']  .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 8']])
universes['Fuel Rod Core 9']  .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 9']])
universes['Fuel Rod Core 10'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 10']])
universes['Fuel Rod Core 11'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 11']])
universes['Fuel Rod Core 12'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 12']])
universes['Fuel Rod Core 13'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 13']])
universes['Fuel Rod Core 14'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 14']])
universes['Fuel Rod Core 15'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 15']])
universes['Fuel Rod Core 16'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 16']])
universes['Fuel Rod Core 17'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 17']])
universes['Fuel Rod Core 18'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 18']])
universes['Fuel Rod Core 19'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 19']])
universes['Fuel Rod Core 20'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 20']])
universes['Fuel Rod Core 21'] .add_cells([cells['Fuel Rod Fuel'], cells['Fuel Rod Gap'],
                                   cells['Fuel Rod Clad'], cells['Fuel Rod Moderator Core 21']])

universes['Al Rod Core 1']    .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 1']])
universes['Al Rod Core 2']    .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 2']])
universes['Al Rod Core 3']    .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 3']])
universes['Al Rod Core 4']    .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 4']])
universes['Al Rod Core 5']    .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 5']])
universes['Al Rod Core 6']    .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 6']])
universes['Al Rod Core 7']    .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 7']])
universes['Al Rod Core 8']    .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 8']])
universes['Al Rod Core 9']    .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 9']])
universes['Al Rod Core 10']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 10']])
universes['Al Rod Core 11']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 11']])
universes['Al Rod Core 12']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 12']])
universes['Al Rod Core 13']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 13']])
universes['Al Rod Core 14']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 14']])
universes['Al Rod Core 15']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 15']])
universes['Al Rod Core 16']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 16']])
universes['Al Rod Core 17']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 17']])
universes['Al Rod Core 18']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 18']])
universes['Al Rod Core 19']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 19']])
universes['Al Rod Core 20']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 20']])
universes['Al Rod Core 21']   .add_cells([cells['Al Rod Al'], cells['Al Rod Moderator Core 21']])

universes['B4C Rod Core 1']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                          cells['B4C Rod Moderator Core 1']])
universes['B4C Rod Core 2']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                          cells['B4C Rod Moderator Core 2']])
universes['B4C Rod Core 3']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                          cells['B4C Rod Moderator Core 3']])
universes['B4C Rod Core 4']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                          cells['B4C Rod Moderator Core 4']])
universes['B4C Rod Core 5']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                          cells['B4C Rod Moderator Core 5']])
universes['B4C Rod Core 6']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                          cells['B4C Rod Moderator Core 6']])
universes['B4C Rod Core 7']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                          cells['B4C Rod Moderator Core 7']])
universes['B4C Rod Core 8']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                          cells['B4C Rod Moderator Core 8']])
universes['B4C Rod Core 9']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                          cells['B4C Rod Moderator Core 9']])
universes['B4C Rod Core 10']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 10']])
universes['B4C Rod Core 11']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 11']])
universes['B4C Rod Core 12']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 12']])
universes['B4C Rod Core 13']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 13']])
universes['B4C Rod Core 14']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 14']])
universes['B4C Rod Core 15']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 15']])
universes['B4C Rod Core 16']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 16']])
universes['B4C Rod Core 17']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 17']])
universes['B4C Rod Core 18']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 18']])
universes['B4C Rod Core 19']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 19']])
universes['B4C Rod Core 20']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 20']])
universes['B4C Rod Core 21']   .add_cells([cells['B4C Rod B4C'], cells['B4C Rod Clad'],
                                           cells['B4C Rod Moderator Core 21']])

universes['Reflector Core 1'] .add_cell(cells['Reflector Core 1'])
universes['Reflector Core 2'] .add_cell(cells['Reflector Core 2'])
universes['Reflector Core 3'] .add_cell(cells['Reflector Core 3'])
universes['Reflector Core 4'] .add_cell(cells['Reflector Core 4'])
universes['Reflector Core 5'] .add_cell(cells['Reflector Core 5'])
universes['Reflector Core 6'] .add_cell(cells['Reflector Core 6'])
universes['Reflector Core 7'] .add_cell(cells['Reflector Core 7'])
universes['Reflector Core 8'] .add_cell(cells['Reflector Core 8'])
universes['Reflector Core 9'] .add_cell(cells['Reflector Core 9'])
universes['Reflector Core 10'].add_cell(cells['Reflector Core 10'])
universes['Reflector Core 11'].add_cell(cells['Reflector Core 11'])
universes['Reflector Core 12'].add_cell(cells['Reflector Core 12'])
universes['Reflector Core 13'].add_cell(cells['Reflector Core 13'])
universes['Reflector Core 14'].add_cell(cells['Reflector Core 14'])
universes['Reflector Core 15'].add_cell(cells['Reflector Core 15'])
universes['Reflector Core 16'].add_cell(cells['Reflector Core 16'])
universes['Reflector Core 17'].add_cell(cells['Reflector Core 17'])
universes['Reflector Core 18'].add_cell(cells['Reflector Core 18'])
universes['Reflector Core 19'].add_cell(cells['Reflector Core 19'])
universes['Reflector Core 20'].add_cell(cells['Reflector Core 20'])
universes['Reflector Core 21'].add_cell(cells['Reflector Core 21'])

universes['SS Sheet Cross Core 11'].add_cells([cells['SS Sheet Cross SS Core 11'], cells['SS Sheet Cross Mod Core 11']])
universes['SS Sheet Horiz Core 11'].add_cells([cells['SS Sheet Horiz SS Core 11'], cells['SS Sheet Horiz Mod Core 11']])
universes['SS Sheet Verti Core 11'].add_cells([cells['SS Sheet Verti SS Core 11'], cells['SS Sheet Verti Mod Core 11']])
universes['SS Sheet Cross Core 12'].add_cells([cells['SS Sheet Cross SS Core 12'], cells['SS Sheet Cross Mod Core 12']])
universes['SS Sheet Horiz Core 12'].add_cells([cells['SS Sheet Horiz SS Core 12'], cells['SS Sheet Horiz Mod Core 12']])
universes['SS Sheet Verti Core 12'].add_cells([cells['SS Sheet Verti SS Core 12'], cells['SS Sheet Verti Mod Core 12']])
universes['BAl Sheet Cross Core 13'].add_cells([cells['BAl Sheet Cross BAl Core 13'], cells['BAl Sheet Cross Mod Core 13']])
universes['BAl Sheet Horiz Core 13'].add_cells([cells['BAl Sheet Horiz BAl Core 13'], cells['BAl Sheet Horiz Mod Core 13']])
universes['BAl Sheet Verti Core 13'].add_cells([cells['BAl Sheet Verti BAl Core 13'], cells['BAl Sheet Verti Mod Core 13']])
universes['BAl Sheet Cross Core 14'].add_cells([cells['BAl Sheet Cross BAl Core 14'], cells['BAl Sheet Cross Mod Core 14']])
universes['BAl Sheet Horiz Core 14'].add_cells([cells['BAl Sheet Horiz BAl Core 14'], cells['BAl Sheet Horiz Mod Core 14']])
universes['BAl Sheet Verti Core 14'].add_cells([cells['BAl Sheet Verti BAl Core 14'], cells['BAl Sheet Verti Mod Core 14']])
universes['BAl Sheet Cross Core 15'].add_cells([cells['BAl Sheet Cross BAl Core 15'], cells['BAl Sheet Cross Mod Core 15']])
universes['BAl Sheet Horiz Core 15'].add_cells([cells['BAl Sheet Horiz BAl Core 15'], cells['BAl Sheet Horiz Mod Core 15']])
universes['BAl Sheet Verti Core 15'].add_cells([cells['BAl Sheet Verti BAl Core 15'], cells['BAl Sheet Verti Mod Core 15']])
universes['BAl Sheet Cross Core 16'].add_cells([cells['BAl Sheet Cross BAl Core 16'], cells['BAl Sheet Cross Mod Core 16']])
universes['BAl Sheet Horiz Core 16'].add_cells([cells['BAl Sheet Horiz BAl Core 16'], cells['BAl Sheet Horiz Mod Core 16']])
universes['BAl Sheet Verti Core 16'].add_cells([cells['BAl Sheet Verti BAl Core 16'], cells['BAl Sheet Verti Mod Core 16']])
universes['BAl Sheet Cross Core 17'].add_cells([cells['BAl Sheet Cross BAl Core 17'], cells['BAl Sheet Cross Mod Core 17']])
universes['BAl Sheet Horiz Core 17'].add_cells([cells['BAl Sheet Horiz BAl Core 17'], cells['BAl Sheet Horiz Mod Core 17']])
universes['BAl Sheet Verti Core 17'].add_cells([cells['BAl Sheet Verti BAl Core 17'], cells['BAl Sheet Verti Mod Core 17']])
universes['BAl Sheet Cross Core 18'].add_cells([cells['BAl Sheet Cross BAl Core 18'], cells['BAl Sheet Cross Mod Core 18']])
universes['BAl Sheet Horiz Core 18'].add_cells([cells['BAl Sheet Horiz BAl Core 18'], cells['BAl Sheet Horiz Mod Core 18']])
universes['BAl Sheet Verti Core 18'].add_cells([cells['BAl Sheet Verti BAl Core 18'], cells['BAl Sheet Verti Mod Core 18']])
universes['BAl Sheet Cross Core 19'].add_cells([cells['BAl Sheet Cross BAl Core 19'], cells['BAl Sheet Cross Mod Core 19']])
universes['BAl Sheet Horiz Core 19'].add_cells([cells['BAl Sheet Horiz BAl Core 19'], cells['BAl Sheet Horiz Mod Core 19']])
universes['BAl Sheet Verti Core 19'].add_cells([cells['BAl Sheet Verti BAl Core 19'], cells['BAl Sheet Verti Mod Core 19']])
universes['BAl Sheet Cross Core 20'].add_cells([cells['BAl Sheet Cross BAl Core 20'], cells['BAl Sheet Cross Mod Core 20']])
universes['BAl Sheet Horiz Core 20'].add_cells([cells['BAl Sheet Horiz BAl Core 20'], cells['BAl Sheet Horiz Mod Core 20']])
universes['BAl Sheet Verti Core 20'].add_cells([cells['BAl Sheet Verti BAl Core 20'], cells['BAl Sheet Verti Mod Core 20']])
universes['BAl Sheet Cross Core 21'].add_cells([cells['BAl Sheet Cross BAl Core 21'], cells['BAl Sheet Cross Mod Core 21']])
universes['BAl Sheet Horiz Core 21'].add_cells([cells['BAl Sheet Horiz BAl Core 21'], cells['BAl Sheet Horiz Mod Core 21']])
universes['BAl Sheet Verti Core 21'].add_cells([cells['BAl Sheet Verti BAl Core 21'], cells['BAl Sheet Verti Mod Core 21']])
